/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/healthz': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {string} */
							status: 'ok';
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/readyz': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {string} */
							status: 'ready';
						};
					};
				};
				/** @description Default Response */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/google/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query: {
					code?: unknown;
					state: string;
					scope?: string;
					authuser?: string;
					prompt?: string;
					error: string;
					error_description?: string;
					error_uri?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							accessToken: string;
							user: {
								id: string;
								googleSubject: string;
								email: string;
								displayName: string | null;
								timezone: string;
							};
							healthSync: {
								queued: boolean;
								/** Format: date */
								from: string;
								/** Format: date */
								to: string;
							};
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				502: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							googleSubject: string;
							email: string;
							displayName: string | null;
							timezone: string;
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						timezone: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							googleSubject: string;
							email: string;
							displayName: string | null;
							timezone: string;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		trace?: never;
	};
	'/api/v1/me/character': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							userId: string;
							name: string;
							classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
							className: string;
							backgroundKey: 'exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper';
							backgroundName: string;
							backgroundTags: ('exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper')[];
							stats: {
								strength: number;
								agility: number;
								vitality: number;
								insight: number;
							};
							flavorTitle: string;
							flavorSummary: string;
							backstory: string;
							/** Format: date-time */
							createdAt: string;
						} | null;
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						name: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							userId: string;
							name: string;
							classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
							className: string;
							backgroundKey: 'exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper';
							backgroundName: string;
							backgroundTags: ('exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper')[];
							stats: {
								strength: number;
								agility: number;
								vitality: number;
								insight: number;
							};
							flavorTitle: string;
							flavorSummary: string;
							backstory: string;
							/** Format: date-time */
							createdAt: string;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/character-creation': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json':
							| {
									/** @enum {string} */
									status: 'in_progress';
									answeredCount: number;
									/** @enum {number} */
									totalQuestions: 8;
									question: {
										id: string;
										prompt: string;
										options: {
											id: string;
											label: string;
										}[];
									};
									preview: null;
							  }
							| {
									/** @enum {string} */
									status: 'ready';
									/** @enum {number} */
									answeredCount: 8;
									/** @enum {number} */
									totalQuestions: 8;
									question: null;
									preview: {
										classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
										className: string;
										backgroundKey: 'exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper';
										backgroundName: string;
										backgroundTags: ('exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper')[];
										stats: {
											strength: number;
											agility: number;
											vitality: number;
											insight: number;
										};
										flavorTitle: string;
										flavorSummary: string;
										backstory: string;
									};
							  };
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/character-creation/answers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						questionId: string;
						answerId: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json':
							| {
									/** @enum {string} */
									status: 'in_progress';
									answeredCount: number;
									/** @enum {number} */
									totalQuestions: 8;
									question: {
										id: string;
										prompt: string;
										options: {
											id: string;
											label: string;
										}[];
									};
									preview: null;
							  }
							| {
									/** @enum {string} */
									status: 'ready';
									/** @enum {number} */
									answeredCount: 8;
									/** @enum {number} */
									totalQuestions: 8;
									question: null;
									preview: {
										classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
										className: string;
										backgroundKey: 'exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper';
										backgroundName: string;
										backgroundTags: ('exile' | 'caretaker' | 'scholar' | 'wanderer' | 'artisan' | 'oathkeeper')[];
										stats: {
											strength: number;
											agility: number;
											vitality: number;
											insight: number;
										};
										flavorTitle: string;
										flavorSummary: string;
										backstory: string;
									};
							  };
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/progression': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							userId: string;
							experience: number;
							level: number;
							nextLevelExperience: number;
							unlocks: {
								unlockType: 'unlock' | 'milestone';
								key: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/inventory': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							currencies: {
								key: string;
								kind: 'currency' | 'item' | 'equipment';
								displayName: string;
								quantity: number;
							}[];
							items: {
								key: string;
								kind: 'currency' | 'item' | 'equipment';
								displayName: string;
								quantity: number;
							}[];
							equipment: {
								key: string;
								kind: 'currency' | 'item' | 'equipment';
								displayName: string;
								quantity: number;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/loadout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							weapon: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
							armor: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
							accessory: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/loadout/{slot}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					slot: 'weapon' | 'armor' | 'accessory';
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						catalogKey: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							weapon: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
							armor: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
							accessory: {
								slot: 'weapon' | 'armor' | 'accessory';
								key: string;
								displayName: string;
								quantity: number;
							} | null;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					slot: 'weapon' | 'armor' | 'accessory';
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							status: ('active' | 'revoked') | null;
							lastSyncAt: string | null;
							healthUserId: string | null;
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/health/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** Format: date */
						from?: string;
						/** Format: date */
						to?: string;
						dataTypes?: ('steps' | 'sleep')[];
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							queued: boolean;
							/** Format: date */
							from: string;
							/** Format: date */
							to: string;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/progress/{localDate}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					localDate: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							userId: string;
							/** Format: date */
							localDate: string;
							rulesetId: string;
							steps: number | null;
							sleepMinutes: number | null;
							movementUnits: number;
							recoveryPoints: number;
							status: 'provisional' | 'complete';
						} | null;
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						}[];
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						name: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/map': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							currentChapter: number;
							currentNodeId: string;
							nodes: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								} | null;
							}[];
							edges: {
								id: string;
								fromNodeId: string;
								toNodeId: string;
								optionKey: string;
								sortOrder: number;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/adventure': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							currentNodeId: string;
							land: {
								key: string;
								chapterNo: number;
								displayName: string;
								description: string;
							};
							currentObjective: {
								key: string;
								displayName: string;
								description: string;
								landmarkKey: string;
							} | null;
							history: {
								landKey: string;
								objectiveKey: string;
								displayName: string;
								description: string;
								landmarkKey: string;
								nodeId: string;
								/** Format: date-time */
								completedAt: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/progress': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							/** Format: date */
							worldDate: string;
							movementUnits: number;
							movementCost: number;
							movementSatisfied: boolean;
							recoveryPoints: number;
							gateContribution: number;
							gateProgress: number;
							gateCost: number;
							gateUnlocked: boolean;
							status: 'provisional' | 'complete';
							members: {
								userId: string;
								movementUnits: number;
								recoveryPoints: number;
								status: 'provisional' | 'complete';
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/progression': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							items: {
								id: string;
								partyId: string;
								nodeId: string;
								nodeName: string;
								resolutionId: string;
								rewardIndex: number;
								reward: {
									experience?: number;
									unlockKey?: string;
									milestoneKey?: string;
									currency?: {
										key: string;
										amount: number;
									};
									item?: {
										key: string;
										quantity: number;
									};
									equipment?: {
										key: string;
									};
								};
								/** Format: date-time */
								createdAt: string;
							}[];
							nextCursor: string | null;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/branch-votes/{nodeId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
					nodeId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							accepted: boolean;
							partyId: string;
							nodeId: string;
							/** Format: date-time */
							deadlineAt: string;
							resolvedEdgeId: string | null;
							votes: {
								userId: string;
								edgeId: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
					nodeId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						edgeId: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							accepted: boolean;
							partyId: string;
							nodeId: string;
							/** Format: date-time */
							deadlineAt: string;
							resolvedEdgeId: string | null;
							votes: {
								userId: string;
								edgeId: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/party-memberships': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						inviteToken: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/invites': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							partyId: string;
							token: string;
							/** Format: date-time */
							expiresAt: string;
							maxUses: number;
							useCount: number;
							revokedAt: string | null;
							/** Format: date-time */
							createdAt: string;
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/invites/{inviteId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
					inviteId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/members/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/members/{memberUserId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
					memberUserId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/leader': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						targetUserId: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							id: string;
							name: string;
							status: 'active' | 'abandoned';
							memberCapacity: number;
							currentNode: {
								id: string;
								chapterNo: number;
								regionNo: number;
								name: string;
								nodeType: 'travel' | 'dungeon' | 'gate' | 'rest' | 'combat' | 'treasure' | 'narrative' | 'village';
								templateKey: string;
								config: {
									movementCost: number;
									obstacleCost: number;
									landmark?: {
										key: string;
									};
									event?:
										| {
												/** @enum {string} */
												eventType: 'combat';
										  }
										| {
												eventType: 'treasure' | 'narrative' | 'rest';
												prompt: string;
												choices: {
													key: string;
													displayName: string;
													description: string;
													requirements: {
														movementUnits: number;
														recoveryPoints: number;
													};
												}[];
										  }
										| {
												/** @enum {string} */
												eventType: 'village';
												settlementKey: string;
										  };
								};
							};
							gateProgress: number;
							decisionStartedAt: string | null;
							members: {
								userId: string;
								role: 'leader' | 'member';
								displayName: string | null;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/village': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							settlement: {
								key: string;
								displayName: string;
								description: string;
							};
							merchant: {
								key: string;
								displayName: string;
								role: string;
							};
							currency: {
								key: string;
								displayName: string;
								balance: number;
							};
							offers: {
								key: string;
								kind: 'item' | 'equipment';
								displayName: string;
								currencyKey: string;
								unitPrice: number;
								ownedQuantity: number;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/village/purchases': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						catalogKey: string;
						quantity: number;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							itemKey: string;
							displayName: string;
							quantity: number;
							unitPrice: number;
							totalPrice: number;
							currency: {
								key: string;
								displayName: string;
								remainingBalance: number;
							};
							inventoryQuantity: number;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/village/departures': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							accepted: boolean;
							partyId: string;
							nodeId: string;
							/** Format: date-time */
							deadlineAt: string;
							resolvedEdgeId: string | null;
							votes: {
								userId: string;
								edgeId: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/encounter': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							/** Format: date */
							worldDate: string;
							status: 'active' | 'completed';
							enemies: {
								id: string;
								archetypeKey: string;
								displayName: string;
								maxHealth: number;
								currentHealth: number;
								pressure: number;
							}[];
							members: {
								userId: string;
								currentHealth: number;
								maxHealth: number;
								classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
								signatureAction: {
									key: 'shield-wall' | 'ambush' | 'volley' | 'mend' | 'arcane-burst' | 'rally';
									displayName: string;
									description: string;
									targetMode: 'enemy' | 'ally' | 'none';
								};
								selectedActionKey: ('shield-wall' | 'ambush' | 'volley' | 'mend' | 'arcane-burst' | 'rally') | null;
								actionMode: 'ability' | 'basic';
								targetEnemyId: string | null;
								targetUserId: string | null;
								targetMode: 'manual' | 'auto' | 'none';
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/encounter/actions/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						actionKey: ('shield-wall' | 'ambush' | 'volley' | 'mend' | 'arcane-burst' | 'rally') | null;
						targetEnemyId: string | null;
						targetUserId: string | null;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							/** Format: date */
							worldDate: string;
							status: 'active' | 'completed';
							enemies: {
								id: string;
								archetypeKey: string;
								displayName: string;
								maxHealth: number;
								currentHealth: number;
								pressure: number;
							}[];
							members: {
								userId: string;
								currentHealth: number;
								maxHealth: number;
								classKey: 'warrior' | 'rogue' | 'ranger' | 'cleric' | 'mage' | 'bard';
								signatureAction: {
									key: 'shield-wall' | 'ambush' | 'volley' | 'mend' | 'arcane-burst' | 'rally';
									displayName: string;
									description: string;
									targetMode: 'enemy' | 'ally' | 'none';
								};
								selectedActionKey: ('shield-wall' | 'ambush' | 'volley' | 'mend' | 'arcane-burst' | 'rally') | null;
								actionMode: 'ability' | 'basic';
								targetEnemyId: string | null;
								targetUserId: string | null;
								targetMode: 'manual' | 'auto' | 'none';
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/item-uses': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						itemKey: string;
						targetUserId: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							itemKey: string;
							targetUserId: string;
							healedAmount: number;
							currentHealth: number;
							maxHealth: number;
							remainingQuantity: number;
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/event': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							/** Format: date */
							worldDate: string;
							eventType: 'narrative' | 'treasure' | 'rest';
							prompt: string;
							choices: {
								key: string;
								displayName: string;
								description: string;
								requirements: {
									movementUnits: number;
									recoveryPoints: number;
								};
							}[];
							selectedChoiceKey: string | null;
							votes: {
								userId: string;
								choiceKey: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/parties/{partyId}/event/choices/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					partyId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						choiceKey: string;
					};
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							partyId: string;
							nodeId: string;
							/** Format: date */
							worldDate: string;
							eventType: 'narrative' | 'treasure' | 'rest';
							prompt: string;
							choices: {
								key: string;
								displayName: string;
								description: string;
								requirements: {
									movementUnits: number;
									recoveryPoints: number;
								};
							}[];
							selectedChoiceKey: string | null;
							votes: {
								userId: string;
								choiceKey: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/integrations/google-health/webhook': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json':
						| {
								data: {
									/** @enum {string} */
									version: '1';
									clientProvidedSubscriptionName: string;
									healthUserId: string;
									operation: 'UPSERT' | 'DELETE';
									dataType: 'steps' | 'sleep';
									intervals: {
										physicalTimeInterval: {
											startTime: string;
											endTime: string;
										};
										civilIso8601TimeInterval: {
											startTime: string;
											endTime: string;
										};
										civilDateTimeInterval?: {
											startDateTime: {
												date: {
													year: number;
													month: number;
													day: number;
												};
												time?: {
													hours?: number;
													minutes?: number;
													seconds?: number;
													nanos?: number;
												};
											};
											endDateTime: {
												date: {
													year: number;
													month: number;
													day: number;
												};
												time?: {
													hours?: number;
													minutes?: number;
													seconds?: number;
													nanos?: number;
												};
											};
										};
									}[];
									recordId?: string;
								};
						  }
						| {
								/** @enum {string} */
								type: 'verification';
						  };
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': unknown;
					};
				};
				/** @description Default Response */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
				/** @description Default Response */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': {
							type: string;
							title: string;
							status: number;
							detail: string;
							instance?: string;
							invalidParams?: {
								name: string;
								reason: string;
							}[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
