/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AppCharacterRouteImport } from './routes/_app/character'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPartiesRouteImport } from './routes/_app/parties'
import { Route as AppProgressionRouteImport } from './routes/_app/progression'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AppPartiesPartyIdRouteImport } from './routes/_app/parties/$partyId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppCharacterRoute = AppCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressionRoute = AppProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPartiesPartyIdRoute = AppPartiesPartyIdRouteImport.update({
  id: '/$partyId',
  path: '/$partyId',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRoute
  '/character': typeof AppCharacterRoute
  '/inventory': typeof AppInventoryRoute
  '/parties': typeof AppPartiesRouteWithChildren
  '/progression': typeof AppProgressionRoute
  '/settings': typeof AppSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/parties/$partyId': typeof AppPartiesPartyIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppRoute
  '/character': typeof AppCharacterRoute
  '/inventory': typeof AppInventoryRoute
  '/parties': typeof AppPartiesRouteWithChildren
  '/progression': typeof AppProgressionRoute
  '/settings': typeof AppSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/parties/$partyId': typeof AppPartiesPartyIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_app/character': typeof AppCharacterRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/parties': typeof AppPartiesRouteWithChildren
  '/_app/progression': typeof AppProgressionRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_app/parties/$partyId': typeof AppPartiesPartyIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/character'
    | '/inventory'
    | '/parties'
    | '/progression'
    | '/settings'
    | '/api/$'
    | '/api/session'
    | '/auth/logout'
    | '/parties/$partyId'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/character'
    | '/inventory'
    | '/parties'
    | '/progression'
    | '/settings'
    | '/api/$'
    | '/api/session'
    | '/auth/logout'
    | '/parties/$partyId'
    | '/auth/google/callback'
    | '/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app'
    | '/_app/character'
    | '/_app/inventory'
    | '/_app/parties'
    | '/_app/progression'
    | '/_app/settings'
    | '/api/$'
    | '/api/session'
    | '/auth/logout'
    | '/_app/parties/$partyId'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiSessionRoute: typeof ApiSessionRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/character': {
      id: '/_app/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof AppCharacterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progression': {
      id: '/_app/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AppProgressionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/parties/$partyId': {
      id: '/_app/parties/$partyId'
      path: '/$partyId'
      fullPath: '/parties/$partyId'
      preLoaderRoute: typeof AppPartiesPartyIdRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPartiesRouteChildren {
  AppPartiesPartyIdRoute: typeof AppPartiesPartyIdRoute
}

const AppPartiesRouteChildren: AppPartiesRouteChildren = {
  AppPartiesPartyIdRoute: AppPartiesPartyIdRoute,
}

const AppPartiesRouteWithChildren = AppPartiesRoute._addFileChildren(
  AppPartiesRouteChildren,
)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppCharacterRoute: typeof AppCharacterRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPartiesRoute: typeof AppPartiesRouteWithChildren
  AppProgressionRoute: typeof AppProgressionRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppCharacterRoute: AppCharacterRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPartiesRoute: AppPartiesRouteWithChildren,
  AppProgressionRoute: AppProgressionRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiSessionRoute: ApiSessionRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
